version: '3'
services:
  db:
    image: postgres:15.6-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=mypguser
      - POSTGRES_PASSWORD=mypgpassword
